apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader-app
spec:
  replicas: 1
  selector: { matchLabels: { app: data-loader-app } }
  template:
    metadata: { labels: { app: data-loader-app } }
    spec:
      containers:
      - name: app
        image: <DOCKERHUB_USER>/data-loader:latest
        ports: [{ containerPort: 8000 }]
        env:
        - name: DB_HOST   ; value: "mysql"
        - name: DB_PORT   ; value: "3306"
        - name: DB_USER   ; valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_USER } }
        - name: DB_PASSWORD; valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_PASSWORD } }
        - name: DB_NAME   ; valueFrom: { secretKeyRef: { name: mysql-secret, key: MYSQL_DATABASE } }
